"""Deterministic family-level documents for semantic retrieval.

The module keeps the reviewed corpus as the only source of authentic FFE text.
Semantic enrichment is optional retrieval-only metadata.  It can add reviewed
concept keywords or retrieval descriptions, but it never changes corpus text,
attestation, or ``Corpus.resolve``.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Mapping

from .corpus import Corpus


class SemanticTextView(str, Enum):
    GLOSS_ONLY = "gloss-only"
    GLOSS_PLUS_CANONICAL = "gloss-plus-canonical"


class SemanticMultiViewProfile(str, Enum):
    """Approved multi-vector document profiles for dense candidate generation."""

    BASE = "multi-view-base"
    ENRICHED = "multi-view-enriched"


@dataclass(frozen=True)
class SemanticEnrichment:
    family_id: str
    keywords: tuple[str, ...] = ()
    scenarios: tuple[str, ...] = ()
    paraphrases: tuple[str, ...] = ()
    usage_notes: tuple[str, ...] = ()
    provenance: str = ""
    review_status: str = "human-reviewed"


@dataclass(frozen=True)
class SemanticVectorView:
    family_id: str
    expression_id: str
    canonical_variant_id: str
    view_name: str
    text: str


@dataclass(frozen=True)
class SemanticDocument:
    family_id: str
    expression_id: str
    gloss: str
    canonical_variant_id: str
    canonical_text: str
    source_id: str
    provenance_status: str
    enrichment: SemanticEnrichment | None = None

    def embedding_text(self, view: SemanticTextView | str = SemanticTextView.GLOSS_ONLY) -> str:
        mode = SemanticTextView(view)
        if mode is SemanticTextView.GLOSS_ONLY:
            return self.gloss
        return f"معنی: {self.gloss}\nعبارت ثبت‌شده: {self.canonical_text}"

    def embedding_views(
        self,
        profile: SemanticMultiViewProfile | str = SemanticMultiViewProfile.BASE,
    ) -> tuple[SemanticVectorView, ...]:
        """Return multiple retrieval-only semantic views for one family.

        BASE contains no added semantic claims: it re-expresses only reviewed
        corpus fields. ENRICHED additionally uses separately reviewed enrichment
        rows when available.  The canonical FFE remains a corpus pointer and is
        never generated by this layer.
        """
        mode = SemanticMultiViewProfile(profile)
        rows = [
            SemanticVectorView(
                self.family_id,
                self.expression_id,
                self.canonical_variant_id,
                "gloss",
                self.gloss,
            ),
            SemanticVectorView(
                self.family_id,
                self.expression_id,
                self.canonical_variant_id,
                "scenario-from-gloss",
                f"موقعیت یا مفهوم کاربردی: {self.gloss}",
            ),
            SemanticVectorView(
                self.family_id,
                self.expression_id,
                self.canonical_variant_id,
                "canonical-plus-gloss",
                f"عبارت ثبت‌شده: {self.canonical_text}\nمعنی: {self.gloss}",
            ),
        ]
        if mode is SemanticMultiViewProfile.ENRICHED and self.enrichment is not None:
            if self.enrichment.keywords:
                rows.append(
                    SemanticVectorView(
                        self.family_id,
                        self.expression_id,
                        self.canonical_variant_id,
                        "reviewed-keywords",
                        "موضوع‌ها و کلیدواژه‌های معنایی: " + "، ".join(self.enrichment.keywords),
                    )
                )
            for index, text in enumerate(self.enrichment.scenarios, 1):
                rows.append(
                    SemanticVectorView(
                        self.family_id,
                        self.expression_id,
                        self.canonical_variant_id,
                        f"reviewed-scenario-{index}",
                        f"موقعیت کاربرد: {text}",
                    )
                )
            for index, text in enumerate(self.enrichment.paraphrases, 1):
                rows.append(
                    SemanticVectorView(
                        self.family_id,
                        self.expression_id,
                        self.canonical_variant_id,
                        f"reviewed-paraphrase-{index}",
                        f"بازگویی معنی: {text}",
                    )
                )
            for index, text in enumerate(self.enrichment.usage_notes, 1):
                rows.append(
                    SemanticVectorView(
                        self.family_id,
                        self.expression_id,
                        self.canonical_variant_id,
                        f"reviewed-usage-{index}",
                        f"کاربرد: {text}",
                    )
                )
        # Deduplicate exact texts while preserving deterministic view order.
        seen: set[str] = set()
        unique: list[SemanticVectorView] = []
        for row in rows:
            normalized = row.text.strip()
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            unique.append(row)
        return tuple(unique)


def load_semantic_enrichment(
    path: str | Path | None,
    corpus: Corpus,
) -> dict[str, SemanticEnrichment]:
    """Load optional retrieval-only enrichment with strict family validation."""
    if path is None:
        return {}
    file = Path(path)
    if not file.exists():
        raise FileNotFoundError(file)
    known = {item.family_id for item in corpus.expressions}
    output: dict[str, SemanticEnrichment] = {}
    allowed = {
        "family_id",
        "keywords",
        "scenarios",
        "paraphrases",
        "usage_notes",
        "provenance",
        "review_status",
    }
    for line_number, line in enumerate(file.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        payload = json.loads(line)
        if set(payload) != allowed:
            raise ValueError(f"semantic enrichment row {line_number} has unexpected schema")
        family_id = str(payload["family_id"])
        if family_id not in known:
            raise ValueError(f"semantic enrichment references unknown family: {family_id}")
        if family_id in output:
            raise ValueError(f"duplicate semantic enrichment family: {family_id}")

        def clean_list(name: str) -> tuple[str, ...]:
            raw = payload[name]
            if not isinstance(raw, list):
                raise ValueError(f"{name} must be a list in enrichment row {line_number}")
            cleaned = tuple(
                dict.fromkeys(str(value).strip() for value in raw if str(value).strip())
            )
            return cleaned

        review_status = str(payload["review_status"]).strip()
        if review_status != "human-reviewed":
            raise ValueError(f"semantic enrichment row {line_number} is not human-reviewed")
        output[family_id] = SemanticEnrichment(
            family_id=family_id,
            keywords=clean_list("keywords"),
            scenarios=clean_list("scenarios"),
            paraphrases=clean_list("paraphrases"),
            usage_notes=clean_list("usage_notes"),
            provenance=str(payload["provenance"]).strip(),
            review_status=review_status,
        )
    return output


def build_semantic_documents(
    corpus: Corpus,
    enrichment: Mapping[str, SemanticEnrichment] | None = None,
) -> tuple[SemanticDocument, ...]:
    """Return one stable document per FFE family in corpus order."""
    enrichment = enrichment or {}
    documents: list[SemanticDocument] = []
    for expression in corpus.expressions:
        canonical = corpus.resolve(expression.expression_id, expression.canonical_variant_id)
        documents.append(
            SemanticDocument(
                family_id=expression.family_id,
                expression_id=expression.expression_id,
                gloss=expression.gloss,
                canonical_variant_id=expression.canonical_variant_id,
                canonical_text=canonical.text,
                source_id=canonical.source_id,
                provenance_status=canonical.provenance_status,
                enrichment=enrichment.get(expression.family_id),
            )
        )
    return tuple(documents)


def build_semantic_vector_views(
    corpus: Corpus,
    *,
    profile: SemanticMultiViewProfile | str = SemanticMultiViewProfile.BASE,
    enrichment: Mapping[str, SemanticEnrichment] | None = None,
) -> tuple[SemanticVectorView, ...]:
    """Flatten deterministic multi-vector views in stable family/view order."""
    rows: list[SemanticVectorView] = []
    for document in build_semantic_documents(corpus, enrichment):
        rows.extend(document.embedding_views(profile))
    return tuple(rows)
